import {
    BanknoteX,
    Box,
    Boxes,
    ChevronDown,
    DiamondPercent,
    Folder,
    GalleryHorizontalEnd,
    Handbag,
    History,
    Home,
    LayoutDashboard,
    ListFilter,
    LucideIcon,
    NotebookPen,
    Package,
    PlusCircle,
    Settings,
    Shield,
    ShoppingBag,
    Upload,
    User,
    
} from "lucide-react";

export const LucideIconsMap: Record<string, LucideIcon> = {
    user: User,
    setting: Settings,
    order: ShoppingBag,
    dashboard: LayoutDashboard,
    home: Home,
    transaction: BanknoteX,
    gallery: GalleryHorizontalEnd,
    package: Package,
    box: Box,
    boxes: Boxes,
    diamond_percent: DiamondPercent,
    handbag: Handbag,
    folder: Folder,
    shield: Shield,
    chevron_down: ChevronDown,
    list_filter: ListFilter,
    upload: Upload,
    "plus-circle": PlusCircle,
    history: History,
    "notebook-pen": NotebookPen
} as const;
