import RootProvider from "@/providers/root-provider";
import "../assets/styles/globals.css";

import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import config from "@/config";
import { cn } from "@/lib/utils";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: {
        template: `%s - ${config.appName}`,
        default: "",
    },
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    maximumScale: 1,
    userScalable: false,
    initialScale: 1,
    themeColor: "#000000",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(geistSans.variable, geistMono.variable, "antialiased", {
                    "debug-screens": config.isDevelopment,
                })}
            >
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    );
}
